In [1]:
import pandas as pd

In [66]:
import os 
os.listdir("Downloads")

['Automated Rain Guard Using Rain SensorRESEARCH PAPER.docx',
 'aws_certificate',
 'circles.pdf',
 'CLOUD COMPUTING.pdf',
 'Data_Analytics_Essentials_certificate_yelurijanani-gmail-com_efc93cdb-6c04-46a7-b3ca-11601d71105d.pdf',
 'Desktop - Shortcut.lnk',
 'desktop.ini',
 'diagram-export-3-9-2026-12_00_12-PM.png',
 'falimy.jpeg',
 'Final Documentation NutriGraph Ai_final.pdf',
 'Final Documentation NutriGraph Ai_final1.pdf',
 'Git-2.51.0.2-64-bit (1).exe',
 'Git-2.51.0.2-64-bit.exe',
 'Janani Yeluri (1).pdf',
 'Janani Yeluri.pdf',
 'janani.jpeg',
 'Janani_Yeluri_Resume.docx',
 'Janani_Yeluri_Resume.pdf',
 'Janani_Yeluri_Resume.pdf.pdf',
 'Mini Project- Batch 18-1 (1).pptx',
 'Mini Project- Batch 18-1 (2).pptx',
 'Mini Project- Batch 18-1.pptx',
 'NutriGraph AI_RESEARCH PAPER (1).docx',
 'NutriGraph AI_RESEARCH PAPER (2).docx',
 'NutriGraph AI_RESEARCH PAPER (3).docx',
 'NutriGraph AI_RESEARCH PAPER (4) (1).docx',
 'NutriGraph AI_RESEARCH PAPER (4).docx',
 'NutriGraph AI_RESEARCH PAPER.docx',
 'python-3.11.2-amd64.exe',
 'R-4.5.2-win.exe',
 'RStudio-2026.01.1-403.exe',
 'sms+spam+collection',
 'sms+spam+collection.zip',
 'SVS&AS (Final draft) Siri.docx',
 'VSCodeUserSetup-x64-1.104.3.exe',
 'WhatsApp Image 2026-05-11 at 8.48.25 PM.jpeg',
 'XC220-G3vv2_1.14.0_0.8.0_UP_BOOT(250317)_2025-03-17_18.56.31.rar',
 'XC220-G3v_1.14.0_0.8.0_Build250624.zip',
 '_certificate_yelurijanani-gmail-com_be74f331-7382-4a34-841a-e04859756ff2.pdf']

In [67]:
import os
os.listdir("Downloads/sms+spam+collection")

['readme', 'SMSSpamCollection']

In [68]:
import pandas as pd
df=pd.read_csv("Downloads/sms+spam+collection/SMSSpamCollection", sep="\t", names=["label","message"])

In [69]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [70]:
df.shape

(5572, 2)

In [71]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [72]:
df["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [73]:
df["message"
    ].head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: message, dtype: object

In [74]:
df["message_lower"]=df["message"].str.lower()

In [75]:
df[["message", "message_lower"]].head()

,message,message_lower
0,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ..."
1,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...
4,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro..."

In [76]:
token=df["message_lower"][0]

In [77]:
print(token)

go until jurong point, crazy.. available only in bugis n great world la e buffet... cine there got amore wat...

In [78]:
token.split()

['go',
 'until',
 'jurong',
 'point,',
 'crazy..',
 'available',
 'only',
 'in',
 'bugis',
 'n',
 'great',
 'world',
 'la',
 'e',
 'buffet...',
 'cine',
 'there',
 'got',
 'amore',
 'wat...']

In [79]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\lenovo\anaconda3\ml\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\lenovo\anaconda3\ml\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\lenovo\anaconda3\ml\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\lenovo\anaconda3\ml\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\lenovo\anaconda3\ml\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\ml\lib\site-packages (from click->nltk) (0.4.6)

In [2]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
stopwords.words('english')[:20]

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been']

In [82]:
sentence="you need to play basketball"
words=sentence.split()

In [83]:
filtered_words=[word for word in words if word not in stopwords.words('english')]
print(filtered_words)

['need', 'play', 'basketball']

In [84]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer

In [48]:
type(vectorizer)

type

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
vectorizer=TfidfVectorizer()

In [59]:
type(vectorizer)

sklearn.feature_extraction.text.TfidfVectorizer

In [60]:
x=vectorizer.fit_transform(df["message_lower"])

In [61]:
print(x.shape)

(5572, 8713)

In [62]:
df.shape

(5572, 3)

In [86]:
y=df["label"]

In [87]:
y.head()

0     ham
1     ham
2    spam
3     ham
4     ham
Name: label, dtype: object

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
x_train, x_test, y_train , y_test = train_test_split(
    x,y,test_size=0.2, random_state=42)

In [90]:
print(x_train.shape)

(4457, 8713)

In [91]:
print(x_test.shape)

(1115, 8713)

In [93]:
from sklearn.naive_bayes import MultinomialNB

In [94]:
model=MultinomialNB()

In [95]:
model.fit(x_train, y_train)

MultinomialNB()

In [96]:
predictions=model.predict(x_test)

In [97]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test, predictions)

In [98]:
print(accuracy)

0.9668161434977578

In [99]:
from sklearn.metrics import classification_report

In [100]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       966
        spam       1.00      0.75      0.86       149

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.96      1115